# Generated by Django 4.0.3 on 2022-09-08 19:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0004_reviewratting'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReviewRatting',
            new_name='ReviewRating',
        ),
    ]
