# Generated by Django 4.0.3 on 2022-09-09 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_reviewratting_reviewrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewrating',
            old_name='ratting',
            new_name='rating',
        ),
    ]
